### ISSUE TITLE
Case Interpreter: improve actions bar

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#226]
## Description 

At this moment there are two actions in the case interpreter bar: **Download** and **Close**.

![image](https://user-images.githubusercontent.com/5751201/140041538-910646c1-330f-4f30-b03f-796a5ead23af.png)

We need to include two more actions:
- Change primary interpretation.
- Refresh the case (to avoid refreshing the page).

Also, we need to display some basic information about the current interpretation.

## Proposed solution

Put all interpreter actions inside a dropdown. The dropdown will be displayed when clicking on a button with the **Actions** title.

To change the primary interpretation, we will display in the first level of the dropdown all available interpretations. If the user clicks on one interpretation, we will change the primary interpretation.

At the left side of the actions button, we will display the ID of the current interpretation and also the number of variants on this interpretation.

## Tasks

- [x] Display the current actions in a dropdown.
- [x] Add **Refresh** action.
- [x] Add list of available interpretations.
- [x] Display current interpretation info.

## Pending actions

- [x] Switch to new notification manager (see issue #248).
- [x] Remove SWAL notification when the primary interpretation is changed (**pending issue**).

**Comment by jmjuanes** [comment]
Moved all actions of the Case Interpreter toolbar to a dropdown (commit 70d6a70): 

![image](https://user-images.githubusercontent.com/5751201/140957193-881c67fe-cc31-42bf-be4e-585bca9d68a6.png)

**Comment by jmjuanes** [comment]
Added option to refresh the clinical analysis info (commit bff265c): 
![image](https://user-images.githubusercontent.com/5751201/141114537-c4136e15-0970-4b93-87e0-9a916c64b552.png)

Also, a notification message is displayed after the clinical analysis is updated: 
![image](https://user-images.githubusercontent.com/5751201/141115142-ce5c4a71-57e1-4181-ac00-3ea7a28afa4f.png)

**Comment by jmjuanes** [comment]
Added list of available interpretations (secondary interpretations) and allowed to change the interpretation by clicking on the dropdown item (commit 38d1027).

![image](https://user-images.githubusercontent.com/5751201/141120330-13cafd70-df8f-4c0b-9b9f-ea3fdc9559ad.png)

A confirmation message is displayed after the interpretation is changed: 

![image](https://user-images.githubusercontent.com/5751201/141120464-07b7916c-8c53-4a38-9e79-0ba695c8df96.png)

**Comment by jmjuanes** [comment]
**TODO**: the confirmation message is duplicated, we should remove the SWAL notification:

![image](https://user-images.githubusercontent.com/5751201/141120751-d50f1146-fd6a-4e0f-ac66-7c776594e4b3.png)

**Comment by jmjuanes** [comment]
Added information about the primary Interpretation (**ID** and **number of primary findings**) in commit 8fd2c6d:

![image](https://user-images.githubusercontent.com/5751201/141298550-00e4a682-f842-4627-b869-750201dfe707.png)

**Comment by jmjuanes** [comment]
Made some final UI improvements in commits 99556eb and 31c0128: 

- Changed size of actions button:

![image](https://user-images.githubusercontent.com/5751201/141299078-90ab6626-9aed-4910-af4b-42273d34533e.png)

- Rename **Download Clinical Analysis** action to **Download**:

![image](https://user-images.githubusercontent.com/5751201/141299335-08fb2bc2-ab88-4e86-b171-509dda3fffd7.png)

- Update refresh confirmation message (now it says **Clinical analysis refreshed** instead of **Clinical analysis updated**): 

![image](https://user-images.githubusercontent.com/5751201/141299631-0fe525bd-6a64-4c61-99ce-ca02ef566282.png)


- Fixed the vertical alignment of the items displayed in the toolbar: 

![image](https://user-images.githubusercontent.com/5751201/141301624-2a286eaf-f6d3-469e-af20-712d3b5f71a6.png)

**Comment by jmjuanes** [comment]
Fixed `clinical-analysis-manager.js` for using the new notification manager instead of SWAL (commit 4869af8).

Now the new notification is displayed when the interpretation is updated instead of displaying the SWAL notifications (commit 8a77857).

![image](https://user-images.githubusercontent.com/5751201/146771013-ca43d08e-619c-4451-9548-cb672299c332.png)

**Comment by pamag** [comment]
## Reviewed

commit: 170cb7c9b1a893debc598949d76234359836b08a

FIXED
