### ISSUE TITLE
Case Interpreter Portal: rename some tabs and steps

### ISSUE THREAD

**Issue by pamagz** [opencb/jsorolla#235]
## Description
In the development meeting 20211104 has been decided to rename some steps and tabs

**Current view**
![image](https://user-images.githubusercontent.com/93584709/140514407-36d2831c-dba6-4812-bef7-a2dc8b4a0b03.png)

## Rename proposal (before 2021-11-18)

- step: Case Info Manager ---> Case Manager
  - tab: General ---> General Info
  - tab: Interpretation_manager ---> move next to General info

## Rename proposal (2021-11-29)

After some commits related to issue #270, the **Overview** tab was moved next to **General Info**. We decided to move it to the last tab and rename other tabs: 
- General Info: **Case Manager**.
- Clinical: **Clinical Data**.

Also, we decided to rename the Case Manager step as **Case Info** instead.

## Tasks

- [x] Rename **General Info** tab as **Case Manager**.
- [x] Rename **Clinical** tab as **Clinical Data**.
- [x] Rename **Case Manager** step as **Case Info**.
- [x] Move **Overview** tab to the last position and make active the **Case Manager** tab by default when entering in the **Case Info** step.

## Related issues

- **In 'Case Info Manager ' change tab "clinical" by "Proband Info"** #228.
- **Case Interpreter: change Clinical tab of the Case Info Manager section** #223.

**Comment by jmjuanes** [comment]
Renamed **Genera** tab to **General Info** and moved **Interpretation Manager** tab next to **General Info** (commit 4b28b32):

![image](https://user-images.githubusercontent.com/5751201/142407501-936392d0-30ab-45df-866d-309b192b0e13.png)

**Comment by jmjuanes** [comment]
- Rename **Case Manager** step to **Case Info** in commit de3be26.
- Rename **General Info** tab to **Case Manager** and **Clinical** tab to **Clinical Data** in commit 7222063.
- Move **Overview** tab to last position in commit e926b13.

![image](https://user-images.githubusercontent.com/5751201/144077061-3242982e-df88-4511-88f5-6f0daf2b48bb.png)

**Comment by pamag** [comment]
reviewed and closed
