### ISSUE TITLE
Some improvements in data-form

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#268]
## Description 

There are some pending improvements in the `data-form` component.

### Allow defining default layout in section level

At this moment the default layout value can be defined in the element or global configuration level, but not in the section level:

https://github.com/opencb/jsorolla/blob/65ac39999899fcc93c4bc3d0c55f7e0ce8c85633/src/webcomponents/commons/forms/data-form.js#L525

This means that if we need to specify a default layout in a section, we will need to provide the `defaultLayout` value to all elements of the section. This can be improved if we also allow to define the default layout in a section level: 

```js
const layout = element?.display?.defaultLayout ?? section?.display?.defaultLayout ?? this.config?.display?.defaultLayout ?? "horizontal";
```

### Modal buttons configuration

Submit and Clear buttons are configured in `config.buttons` section, but for modal mode the buttons configuration are extracted from `config.display.mode.buttons` instead:

https://github.com/opencb/jsorolla/blob/65ac39999899fcc93c4bc3d0c55f7e0ce8c85633/src/webcomponents/commons/forms/data-form.js#L1297-L1299

We need to unify the buttons configuration in only one place: buttons text will be configured in `config.buttons` and style will be configured in `config.display`.

### Buttons styles

Buttons styles used in `data-form` can be defined in `config.buttons.classes` and `config.buttons.styles`. We suggest moving this configuration to `display` and keep only in the `buttons` field the text displayed in the buttons.

### Data-form mode

At this moment the mode of the `data-form` can be specified in `config.display.mode.type`. But in all instances of `data-form` where we need a specific mode, we ended providing an object with a single field (`type`): 

```
display: {
    mode: {
        type: "modal",
    },
},
```

To simplify this, we suggest reusint the `config.type` field to store the form mode, because the `type: "form"` has no effect at this moment in the data form.

### Help text

At this moment the text of the help block is defined in `help.text`, but there are other elements like validations that use `validation.message` instead. 

### Uniform class names and styles properties

There are some configurations that uses `classes` to provide custom class names, and other configurations uses `classNames`. We suggest to follow the same pattern and always use `className` and `style` to provide global class names, and `buttonsClassName` and `buttonsStyle` when applied to specific elements.

### Uniform title and description fields

In the root configuration we are storing the title in `config.title` and the description in the `config.description` field, but in the section level the description is stored in `section.text` and in the element level is in `element.name`. We suggest following the same criteria and use `element.title` and `section.description` instead of `element.name` and `section.text`.

### Visibility

Rename visibility properties like `showTitle` as `titleVisible`.

## Final configuration object

With the proposed changes, the configuration object for `data-form` will be the following: 

```
{
    title: "",
    description: "",
    icon: "",
    type: "modal", // DEPRECATE OLD "form" value
    buttons: {
        okText: "",     // DEPRECATED --> display.buttonOkText
        clearText: "", // DEPRECATED --> display.buttonClearText
        show: true, // DEPRECATED --> display.buttonsVisible
        top: false, // DEPRECATED --> display.buttonsLayout
    },
    display: {
        className: "",
        style: "",
        buttonsClassName: "",
        buttonsStyle: "",
        buttonsVisible: true,
        buttonsLayout: "bottom",
        buttonsWidth: 12,
        buttonsAlign: "right",
        buttonOkText: "",
        buttonClearText: "",
        mode: "", // DEPRECATED --> type
        defaultValue: "",
        defaultWidth: 12,
        defaultLayout: "",
        layout: [
            {
                id: "",
                className: "",
                style: "",
            },
        ],
        labelWidth: 3,  // DEPRECATED --> titleWidth
        width: 12,
        errorIcon: "",
        errorMessage: "",
        helpIcon: "",
        titleClassName: "",
        titleStyle: "",
        titleVisible: true,
        titleWidth: 3,
        showTitle: true, // DEPRECATED --> titleVisible
        modalWidth: "768px",
        modalDisabled: false,
        modalButtonClassName: "",
        modalButtonStyle: "",
    },
    validation: {
        validate: () => true,
        message: "",
    },
    sections: [
        {
            id: "",
            title: "",
            text: "", // DEPRECATED --> description
            description: "",
            display: {
                labelWidth: 3, // DEPRECATED --> titleWidth
                errorIcon: "",
                errorMessage: "",
                helpIcon: "",
                titleHeader: "h3",
                titleWidth: 3,
                titleClassName: "",
                titleStyle: "",
                textClassName: "", // DEPRECATED --> descriptionClassName
                textStyle: "",     // DEPRECATED --> descriptionStyle
                descriptionClassName: "",
                descriptionStyle: "",
                className: "",
                style: "",
                leftColumnWidth: 6,       // DEPRECATED: use layout instead
                rightColumnWidth: 6,      // DEPRECATED: use layout instead
                columnSeparatorStyle: "", // DEPRECATED: use layout instead
                defaultLayout: "",
                visible: true,
            },
            elements: [
                {
                    type: "",
                    name: "", // DEPRECATED --> title
                    title: "",
                    text: "",
                    field: "",
                    required: true,
                    allowedValues: [],
                    showLabel: true, // DEPRECATED --> display.titleVisible
                    display: {
                        className: "",
                        style: "",
                        visible: true,
                        disabled: false,
                        rows: 1,
                        errorIcon: "",
                        errorMessage: "",
                        helpIcon: "",
                        helpMessage: "",
                        helpMode: "block",
                        defaultValue: "",
                        defaultLayout: "",
                        width: 12,
                        defaultWidth: 12,
                        labelAlign: "left",  // DEPRECATED --> titleAlign
                        labelWidth: 3,       // DEPRECATED --> titleWidth
                        labelClassName: "",  // DEPRECATED --> titleClassName
                        labelStyle: "",      // DEPRECATED --> titleStyle
                        titleAlign: "left",
                        titleWidth: 3,
                        titleClassName: "",
                        titleStyle: "",
                        titleVisible: true,
                        textClassName: "",
                        textStyle: "",
                        placeholder: "",
                        render: () => null,
                        onText: "",
                        offText: "",
                        activeClassName: "",
                        inactiveClassName: "",
                        template: "",
                        contentLayout: "bullets",
                        separator: "",
                        errorClassName: "",
                        transform: () => null,
                        hideHeader: false, // DEPRECATED --> use headerVisible
                        headerVisible: false,
                        columns: [
                            {
                                name: "",  // DEPRECATED: use title instead
                                title: "",
                                className: "",
                                style: "",
                                defaultValue: "",
                                field: "",
                                type: "",
                                render: () => null,
                                format: "",
                            }
                        ],
                        data: [
                            {
                                key: "",
                                value: "",
                            }
                        ],
                        sort: true,
                        highcharts: {},
                        apply: () => null,
                    },
                    validation: {
                        validate: () => true,
                        message: "",
                    },
                },
            ],
        },
    ],
};
```

## Tasks

- [x] Allow defining `defaultLayout` also in the section.
- [x] Get modal buttons configuration from `config.buttons` instead of `config.display.mode.buttons`.
- [x] Reuse the `config.type` field to store the form mode (previously in `config.display.mode.type`).
- [x] Move help configuration to `display.helpIcon` and `display.helpMessage`.
- [x] Move buttons styles configuration to `display` field.
- [x] Rename `classes` to `className` and `styles` to `style`.
- [x] Use `title` and `description` in configuration, section and element levels.
- [x] Remove `<form>` tags.
- [x] Elements must accept only a single array level.
- [x] Move buttons configuration to `condig.display`. See https://github.com/opencb/jsorolla/issues/268#issuecomment-998744594.

**Comment by jmjuanes** [comment]
There are other configuration fields in `display.mode` that are needed for some admin components: 

https://github.com/opencb/jsorolla/blob/8917662163288337a68aef11c735d3090e0e375c/src/webcomponents/commons/forms/data-form.js#L1303-L1305

https://github.com/opencb/jsorolla/blob/8917662163288337a68aef11c735d3090e0e375c/src/webcomponents/commons/forms/data-form.js#L788-L814

Moved issue to **blocked** until we found a solution for this.

**Comment by jmjuanes** [comment]
After reviewing this issue, we decided to move the buttons configuration from `config.buttons` to `config.display`, so now the buttons text configuration must be defined in: 

- `config.display.buttonOkText` for the text in the OK button.
- `config.display.buttonCancelText` for the text in the cancel button.

**Comment by pamag** [comment]
## Reviewed 

OK
