### ISSUE TITLE
Add Panel Intersect option to Variant Browser

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#274]
## Description

There is a new parameter in OpenCGA to allow the intersection of panels with Regions, Genes, and Xrefs (see issues #205 and opencb/opencga#1847). We need to display this parameter in the **Clinical** filters section of the **Variant Browser**.

## Tasks

- [x] Add `panelIntersection` parameter to **Clinical** filters.
- [x] Automatically enable and prevent changing this option in the **Sample Variant Browser** when panel lock is enabled.
- [x] Change the warning message when panel lock is enabled: display the panels and panelIntersect options but keep them disabled.

**Comment by jmjuanes** [comment]
Added **Panel Intersect** filter to Disease panels filter group (commit 4463455): 

![image](https://user-images.githubusercontent.com/5751201/143870328-e917af54-466c-4dc7-be45-cc466baedd97.png)

**Comment by jmjuanes** [comment]
Added description and change panel intersection title in commit bcf1dcd

![image](https://user-images.githubusercontent.com/5751201/143913015-6749a993-ba89-48d6-b514-607308c2f8f1.png)

**Comment by jmjuanes** [comment]
Automatically enable and lock the `panelsIntersect` param if panel lock is enabled (commit a52d72b):

![image](https://user-images.githubusercontent.com/5751201/143916619-8d7e590e-1ae1-49c4-9730-252046b3cfd6.png)

**Comment by pamag** [comment]
## Reviewed

commit: f104bd4712825f4c4fdc278c088a4b7b7bff1bf0

FIXED
