### ISSUE TITLE
Admin: Improvements Clinical and Variants Configurations

### ISSUE THREAD

**Issue by Rodielm** [opencb/jsorolla#276]
## Description

There is a new structure for the modal configurations of the data form related to issue #268, which could improve the configs of the clinical and variant configurations. This requires some changes to the admin configs.

### Before
The change will be affected because in that case `mode` is of type object.
https://github.com/opencb/jsorolla/blob/8e7c2895a1f95bdd67ae7c9cb6eb0ddeb33eb3ab/src/webcomponents/study/configuration/study-clinical-config.js#L272

### After
For the transition of the new changes to the issue #268 , it will be easy to modify the mode, instead of an object it will be a string.

https://github.com/opencb/jsorolla/blob/303459b3b1b15e8e0d6e7f37241ee39eac1e46a3/src/webcomponents/study/configuration/study-clinical-config.js#L273

## Task 

- [x] remove renderBtnGroup from data-form (After the change, it will be unused)
- [x] remove the "custom modal config" 
- [x] Isolate the delete button from the "custom modal config"
- [x] implement the new change when issue #268  is complete

**Comment by pamag** [comment]
see #362 #361

**Comment by Rodielm** [comment]
Fixed 0491eb3
The new `data-form` configuration has been implemented to the clinical and variant configuration components and the UI has been fixed.

**Comment by pamag** [comment]
## Reviewed
    OpenCGA commit:
        58c76ae9a5
    IVA commit:
        a100ebd81423c38600013acd98a51e14a7b51309

DONE but still work on progress for 2.3
