### ISSUE TITLE
Improve jsorolla workflow

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#287]
## Description

At this moment we have two workflows in JSorolla:
- `main.yml`: dispatched every time we push to the `develop` branch. Generates and publishes a docker with the development version of jsorolla and publishes it to the university server.
- `release.yml`: dispatched on each release of jsorolla.

Also, some of the jobs are duplicated in both workflows (for example the build job), and other jobs are very similar to other jobs in CellBase or OpenCGa (docker publish).

## Proposed improvement

- [x] Rename `main.yml` workflow to `develop.yml`.
- [x] Avoid duplication [reusing existing workflows](https://docs.github.com/es/actions/learn-github-actions/reusing-workflows):
  - [x] Create a reusable build workflow.
  - [x] Reuse some of the workflows created in the [java-common-libs](https://github.com/opencb/java-common-libs/tree/develop/.github/workflows) repository.
- [x] Automatically trigger the `develop` workflow on push to the `develop` and `release-*` branches.

**Comment by jmjuanes** [comment]
Warning displayed when running `develop` workflow: 

![image](https://user-images.githubusercontent.com/5751201/146021814-e4b4d8c8-95ce-43da-9d29-e12da6d6e4b2.png)

**TASK**: verify the path to `jsorolla-2.3.0-dev.tar.gz`.

**Comment by pamag** [comment]
## Reviewed
Done
