### ISSUE TITLE
Review: Jsorolla build process

### ISSUE THREAD

**Issue by Rodielm** [opencb/jsorolla#288]
## Description

The build process shows some warning messages about exports and dependency libraries.  This should be fixed before an error or malfunction occurs.

![image](https://user-images.githubusercontent.com/10471758/145814339-70cad48a-b20c-4109-812d-f8f786d5e7a3.png)
![image](https://user-images.githubusercontent.com/10471758/145814437-992c7c13-2b86-43a7-bce6-a67817be10e1.png)

## Tasks  
- [x] Plugin minify-html-literals: splitHTMLByPlaceholder() must return same number of strings as template parts 
- [x] Circular dependencies
- [x] `this` has been rewritten to `undefined`
- [x] Import of non-existent export

**Comment by Rodielm** [comment]
## Solution 

### - Circular Dependencies 

The problem was a file A is importing B and file B is importing A... so this created a Circular Dependency. 

- `-- UtilsNews.Js --> NotificationQueue --> UtilsNews.js`

Thanks to the new notification manager the use NotificationQueue will be avoided, so it will soon be removed... 
 https://github.com/opencb/jsorolla/commit/fb14cac1247f4a7c0e642c5cdb181c5c3db4d55c#diff-88f0c2d3d0bd8ab6d12d54282dd7762966fb375d7d00ec27b3f838ded947b560L341

- `-- Analysis-registry --> opencga-knockout-analysis  --> analysis-registry` and similar things.

To avoid this, the configuration and the component have been split into a separate file.  https://github.com/opencb/jsorolla/commit/e1ad4342ca9b49f32e5b15c0e0f71f6e85e6d7d5

### - this has been rewritten to undefined

A new configuration has been added to the rollup for some third libraries that have this problem.

https://github.com/opencb/jsorolla/commit/9069cc66f619a7865f6cf9e0cb50aa6dbea43332#diff-6814bf77564b4f1c92f5861e184e28fe217c080a047fefa8b73a728f755ec45cR124

-- Reference: https://rollupjs.org/guide/en/#error-this-is-undefined

### - Import of non-existent export

Unnecessary imports or non-existent exports such as this one have been eliminated.

![image](https://user-images.githubusercontent.com/10471758/147161508-4a9ad0ad-457f-4400-bd30-6a2b95d82f66.png)


### - splitHtmlByPlaceholder


Two problems have been encountered.

- The first one is about invalid binding position for the expression

Solution: Just add backslash (`\`) character for the expression https://github.com/opencb/jsorolla/commit/215424872143a3e36e0dc6d56c926193e2ae93b6

Reference: https://github.com/43081j/eslint-plugin-lit/blob/master/docs/rules/binding-positions.md

- The second is possibly caused by the loop inside the expression in html, If you remove the loop inside the html, the warning disappears. However, the problem must have a different cause or maybe it's a bug in the rollup itself. 

Ex:https://github.com/opencb/jsorolla/blob/51f85da2dec1f4de8e1867143e74ba6644888a86/src/webcomponents/opencga/catalog/variableSets/opencga-variable-selector.js#L177

Results: 
![image](https://user-images.githubusercontent.com/10471758/147162849-a1474b9c-b7f2-4f1f-9756-bdca9b8d336b.png)

**Comment by pamag** [comment]
## Reviewed
    OpenCGA commit:
        4947bd62b3bed373d7adac94c45d365bdce59c56
    IVA commit:
        5c977089ff901105e67c92157eac77f31afd8970

FIXED
