### ISSUE TITLE
Allow to lock (or unlock) a case in the main case portal page

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#296]
## Description

At this moment the only way to lock a case is in the **Case Manager** section. That means that if we want to lock some cases, we need to enter each case, lock and save the case and then go back to the case portal page. 

## Proposed improvement

We suggest adding the possibility to lock and unlock a case in the **Actions** menu of the case portal:

![image](https://user-images.githubusercontent.com/5751201/146815621-4b9ffd35-3cfd-4cde-832f-58f21c48b213.png)

## Tasks

- [x] Add **lock / unlock** option to the Actions menu.
- [x] Display a lock icon in the case name if the case is locked.
- [x] Disable selects to change the status and the priority if the case is locked.

**Comment by jmjuanes** [comment]
Allow to lock and unlock a case from the actions menu in the case analysis grid (commit 0aefb4b): 

![Peek 2021-12-21 19-38](https://user-images.githubusercontent.com/5751201/146981945-8ce185a5-9e38-4cd5-80e1-75bab5260ed1.gif)

**Comment by jmjuanes** [comment]
Added an icon before the case ID to indicate if the case is locked (lock icon) or unlocked (unlock icon) in commit 934751e:

![image](https://user-images.githubusercontent.com/5751201/146982992-7ea74349-e08c-45e7-95da-4e77d2723b0a.png)

**Comment by jmjuanes** [comment]
Lock the **Status** and **Priority** selects when the case is locked (commit 8385c31):

![image](https://user-images.githubusercontent.com/5751201/146987943-4619dc7f-1062-4732-8e44-d534e1592f91.png)

**Comment by jmjuanes** [comment]
Changed lock icon position to the right of the case ID (commit 61ddf46):

![image](https://user-images.githubusercontent.com/5751201/147075914-4d04c09a-3167-4a99-822b-5076144a8f6b.png)

**Comment by jmjuanes** [comment]
Displaying a lock icon after the Case ID **only** if the case is locked (commit 2f41610): 

![image](https://user-images.githubusercontent.com/5751201/147223231-c22e5df5-d965-4d3c-8d89-aa26cd930cdd.png)

**Comment by pamag** [comment]
## Reviewed

commit 2f416106a9c21dd1cb6cd9bef3d69318ee53a2eb

Done
