### ISSUE TITLE
Recycle old Notification Utils

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#299]
## Description

At this moment there is an old `NotificationUtils.js` file in the `src/webcomponents` folder. This notification utils is part of the old notifications system.

## Proposed improvement

Recycle these old notification utils for using the new notifications system introduced as part of issue #248. We will add a utility function for dispatching notifications, instead of calling the `LitUtils.dispatchCustomEvent`.

### Constants

We will create the notification types constants, to avoid writing the notification type as a string:

```javascript
const NOTIFY = "notify";
const NOTIFY_SUCCESS = "notifySuccess";
const NOTIFY_ERROR = "notifyError";
const NOTIFY_WARNING = "notifyWarning";
const NOTIFY_INFO = "notifyInfo";
const NOTIFY_RESPONSE = "notifyResponse";
```

### NotificationUtils.dispatch

We will add a `dispatch` function for dispatching a notification. This function needs the following arguments:

- `context`: the instance of the component.
- `type`: the notification type, for example `NotificationUtils.NOTIFY_ERROR`.
- `config`: an object with the configuration of the notification.

Internally this will call `LitUtils.dispatchCustomEvent`.

Example for dispatching an error notification:

```javascript
NotificationUtils.dispatch(this, NotificationUtils.NOTIFY_ERROR, {
    title: "Error!",
    message: "Something went wrong...",
});
```

## Tasks 

- [x] Move the old notifications utils to `src/webcomponents/commons/utils/notification-utils.js`.
- [x] Create notification constants.
- [x] Create notification dispatcher.
- [x] Update `iva-app` and `rest-app`.
