### ISSUE TITLE
Update and fill all sections in ABOUT drop down menu.

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#310]
## Describe the Tasks

ABOUT section in the IVA top bar needs to be updated.

## Tasks

- [ ] (1) the items in the drop down menu are different for unloged or logged sessions.

![image](https://user-images.githubusercontent.com/167875/147231801-29de5946-bf4f-42f0-8d01-79bad832d61a.png)

- [ ] (2) source and release items are pointing to IVA repo instead jsorolla repo
![image](https://user-images.githubusercontent.com/167875/147232332-b0c82f86-cae2-438c-9152-942c6963cb26.png)

fix:
- source: https://github.com/opencb/jsorolla
- release: https://github.com/opencb/jsorolla/releases   
  - jsorolla doesn't have releases yet
  - but has the tags https://github.com/opencb/jsorolla/tags
    
![image](https://user-images.githubusercontent.com/167875/147233310-050357b6-4e7f-4665-94d5-794fae90b05b.png)
 

- [ ] (3) Documentation and Tutorial points to http://docs.opencb.org/display/iva -> too old

- Documentation page is almost 3 years old
![image](https://user-images.githubusercontent.com/167875/147232748-80136684-8f84-4ed3-baef-a74b8ca4de1b.png)

- Tutorial is empty -> there are newer docs at gitdoc: **please update**

- [ ] (4) about, terms, contact, getting started and FAQ are empty 
They are pointing to iva pages like  /iva/#contact

- [ ] (5) REST API is pointing to the new API docs page (under development) instead of swagger 
![image](https://user-images.githubusercontent.com/167875/147235339-669d0880-6530-4c81-8cde-9a902c1de734.png)

**Comment by pamag** [comment]
This about should be a mock up as each installatin would have their own custom configurations.
