### ISSUE TITLE
Feat: Disease Panel Browser

### ISSUE THREAD

**Issue by Rodielm** [opencb/jsorolla#341]
## Description

To facilitate the use and search for information on the disease panel, we will add the disease panel browser, which will be similar to other browsers to make it easier for users to use. 

The disease panel browser contains the following functionalities:

- **Disease panel filters:** A component to find information in the disease panel with different filters.
- **Disease panel grid:**  A component that displays a grid over the disease panel that users search for by filters.
- **Disease panel detail:** A component that displays related information or more specific data that the user searches for about the disease panel.
- **Disease panel view:** A component that displays more specific data that the user searches for about the disease panel.
- **Create and update disease panel:** A component that allows the user to create and update the disease panel.

## Task

- [x] Disease Panel filter
- [x] Disease Panel grid
- [x] Disease Panel detail
- [x] Disease Panel view
- [x] ~~Disease Panel Create~~ **Move to 2.3**
- [x] ~~Disease Panel Update~~ **Move to 2.3**

**Comment by pamag** [comment]
## Reviewed
    OpenCGA commit:
        58c76ae9a5
    IVA commit:
        a100ebd81423c38600013acd98a51e14a7b51309

DONE  with issues:

- the export tab is missing the stats
```
[0] id = Early_onset_dystonia-PanelAppId-192
[1] name = Early onset dystonia
[2] stats.genes = 
[3] stats.regions = 
[4] stats.variants = 
[5] source.author = Genomics England
[6] source.project = PanelApp
[7] source.version = 1.81
```

- Filter categories: what data it contains?
![image](https://user-images.githubusercontent.com/167875/158674200-a4f09b77-d170-4e78-a602-f5444dc563e7.png)

**Comment by Rodielm** [comment]
Supports categories autocomplete

![image](https://user-images.githubusercontent.com/10471758/158800099-ac6d1d7b-c46a-472e-832d-50aa2bf979ef.png)

**Comment by pamag** [comment]
## Reviewed
    OpenCGA commit:
        4947bd62b3bed373d7adac94c45d365bdce59c56
    IVA commit:
        8ddfb063a7a144035504933ad94e807ba2e5e4ae
