### ISSUE TITLE
Improvements and fixes in Rearrangement Variant Browser

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#353]
## Description

We need to do some improvements and fixes in the **Rearrangement Variant Browser**.

### Fix displayed columns layout and allow to select rearrangements

At this moment we can not select a rearrangement in the RVB grid component because the **Select** column is empty:

![image](https://user-images.githubusercontent.com/5751201/149986599-71a0a95e-926a-4578-8407-9929163629f0.png)

This is something that was fixed in other browsers but not in the RVB (see issue #250).

### Save rearrangements selection

Other browsers allow saving the variants selection as primary findings. In the case of rearrangements, each selection is a pair of variants, so we need to save each pair of variants in the primary findings.

### Primary findings review

The step for reviewing the selected variants (primary findings) only works for single variants, not rearrangements. We need to update this view to allow displaying also rearrangements (using the `variant-interpreter-rearrangement-grid` component).

The main idea is to group primary findings into tabs, using the same tabs as in the **Sample Variant Browser**: 

![image](https://user-images.githubusercontent.com/5751201/151546002-1c56a3b9-2c37-4585-b0fc-3a9759ecc4bd.png)

### Report update

We will need to update the table that displays the selected rearrangements to use the `variant-interpreter-rearrangement-grid` instead.

## Tasks

- [x] Fix columns in `variant-interpreter-rearrangement-grid` to allow selecting a rearrangement.
- [x] Allow saving each pair of variants of the rearrangements using the **Save** button.
- [x] Redesign the **Interpretation Review** step for displaying also selected rearrangements.
- [x] Fix report for displaying selected rearrangements.

**Comment by jmjuanes** [comment]
Fixed columns in variant rearrangement grid component in commit aee66bc: 

![image](https://user-images.githubusercontent.com/5751201/150100310-9649d246-78aa-4bce-8eea-5308aee6032c.png)

**Comment by jmjuanes** [comment]
Allow to save selected variants in the rearrangements browser on commit 4c117e4: 

![image](https://user-images.githubusercontent.com/5751201/151578321-2d3472d4-391f-4d12-b1e1-41a9b8308023.png)

**Comment by jmjuanes** [comment]
Add **Somatic Rearrangements** tab in **Interpretation Review** step:

![image](https://user-images.githubusercontent.com/5751201/151775190-13a46321-d872-4fd7-8cb2-292ba73b1b9b.png)

**Comment by pamag** [comment]
## Reviewed
    OpenCGA commit:
        58c76ae9a5
    IVA commit:
        a100ebd81423c38600013acd98a51e14a7b51309


DONE
