### ISSUE TITLE
Conditional highlight in variant browsers

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#369]
## Description

Some users have requested the option to highlight variants in the variant browser that matches a condition (for example having a `depth < 50` or if the `filter` field is not `PASS`).

## Proposed solution

To allow each user to customize how the conditional formatting is applied, we decided to:

- Add a new `highlights` section in the variant browser settings file where we can put the conditions defined by the user.
- Add a new `activeHighlights` section in the variant browser settings file where the user can define the default active hightlights.
- Add a new section the Settings modal of the variant browser to allow the user to decide which conditional formattings will be applied to the displayed variants.

### Configuration

To allow customize the highlight conditions, we will add a new `highlights` section in the variant browser settings file with the conditions that will be available:

```javascript
{
    highlights: [
        {
            id: "highlight1",
            name: "Condition name",
            description: "Condition description",
            condition: variant => {
                return true; // Custom comdition
            },
            style: {
                // Icon style
                icon: "warning",
                iconColor: "red",
                // Row style
                rowBackgroundColor: "#123456",
                rowOpacity: 0.5,
            },
        }
    ],
}
```

Also, an additional `activeHighlights` field can be provided in the settings to define the default active highlights:

```javascript
{
    activeHighlights: ["highlight1", "highlight2"],
}
```

### Displaying icons

We allow also to display an icon in each variant. The icon can be configured using the `style.icon` and `style.iconColor` and will be placed inline with the variant ID.

Icons gallery: https://fontawesome.com/v5.15/icons?d=gallery&p=2 

## Tasks

- [X] Explore `bootstrap-table` API to allow row highlight. **Update**: see comment https://github.com/opencb/jsorolla/issues/369#issuecomment-1022331661 
- [X] Add highlight conditions in variant browser settings.
- [X] Display highlight conditions in the settings modal of variant browser.
- [X] Apply conditional highlight to rows of variant browser grid (highlight and icon).

**Comment by jmjuanes** [comment]
## Bootstrap table API exploration

There is an option for the bootstrap table to customize the row style: https://bootstrap-table.com/docs/api/table-options/#rowstyle 

In the `rowStyle` option we can provide a function that will be called for each displayed row data, and we should return the styles that want to apply to the provided row. The return value of this function must be an object that can contain:

- A field called `classes`, with the CSS classname to apply to this row.
- A field called `style` containing the styles to apply to the row.


Example: https://examples.bootstrap-table.com/#options/row-style.html

**Comment by jmjuanes** [comment]
First implementation of the row highlight feature: 

![image](https://user-images.githubusercontent.com/5751201/152342666-2c52dacc-16a7-4a94-9daa-7c8b13c44393.png)

Highlights can be configured in the **Settings** modal of the variant browser grid: 

![image](https://user-images.githubusercontent.com/5751201/152343045-d9d72c36-5790-40cf-904d-aa6b340c9fd3.png)

**Comment by jmjuanes** [comment]
Display icons and updated highlight configuration: 

![image](https://user-images.githubusercontent.com/5751201/152828560-faecb075-9ca9-492e-b555-6852f8f8a312.png)

**Comment by jmjuanes** [comment]
Displaying a warning message if no highlight conditions are defined in the browser configuration: 

![image](https://user-images.githubusercontent.com/5751201/153388218-ed7edd65-2db8-48cd-8701-029be9ca64d6.png)

**Comment by pamag** [comment]
## Reviewed 

Not able to review

@jmjuanes I need  the demo estudiesto to have configured some highlights, please
![image](https://user-images.githubusercontent.com/167875/154860293-5d07b367-2c65-4958-a78f-27a0a9eaaa72.png)

@Rodielm  Are the highlight conditions  configurable in the Admin Manager?

**Comment by jmjuanes** [comment]
> Are the highlight conditions configurable in the Admin Manager?

@pamag No, highlight conditions can be only configured in the variant browser settings file, as described in the **Configuration** section of the issue. 

Example: https://github.com/opencb/jsorolla/blob/d9e6361573f2980abc3c802b38eb792a8b31ea78/src/sites/iva/conf/opencga-variant-browser.settings.js#L64-L79

**Comment by pamag** [comment]
## Action
- [ ] In order to be able to test this feature we need to create several defaults examples (RD and Cancer)

**Comment by jmjuanes** [comment]
Added default highlight configuration for RD and Cancer SNV browsers in commits 8c1065a and 5b53e15. This is the default configuration applied: 

In **Cancer SNV Browser**:

https://github.com/opencb/jsorolla/blob/5b53e154f188d944cc68db2b2c4bbd9228aebf11/src/sites/iva/conf/variant-interpreter-browser-cancer-snv.settings.js#L49-L68

In **RD Browser**: 

https://github.com/opencb/jsorolla/blob/5b53e154f188d944cc68db2b2c4bbd9228aebf11/src/sites/iva/conf/variant-interpreter-browser-rd.settings.js#L46-L65
