### ISSUE TITLE
Create a CNV Variant Browser

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#381]
## Description

We need to create a new variant browser for displaying only **CNV** variants. 

### Design

The **CNV Variant Browser** will be very close to the **Cancer Variant Browser**, but in this case all displayed variants will have `type="COPY_NUMBER"`. For that reason, the filter `type` will be locked on this browser.

### Displaying genes

CNVs will involve large regions, so there will be a large list of genes that are affected. For that reason, we need to limit the number of displayed genes in the Gene column to the first 10 genes and allow to display the rest of the genes adding a link with the pattern `... show more genes (xxxxx)`.

## Tasks

- [x] Create the new **CNV Variant Browser** using the default `variant-interpretation-grid` component.
- [x] Update genes grid formatter for displaying only up to 10 genes.
- [x] Display filters only for CNV Variant callers.
- [x] Display only VCF columns form CNV Variant callers.

**Comment by jmjuanes** [comment]
Initialized the new **CNV Variant Browser** and lock the `type` filter to the fixed value `COPY_NUMBER` in commit 0d18227:

![image](https://user-images.githubusercontent.com/5751201/151786638-08a27e17-394f-4831-aa53-18b4a484a8f1.png)

**Comment by jmjuanes** [comment]
- Limit the number of displayed genes in **Genes** column in commits f3493d7 and c9e1424.
- Display filters for CNV variant callers in commit b710800.

![image](https://user-images.githubusercontent.com/5751201/155691574-15cdafaf-4102-4828-a3cd-fe3a1582ae77.png)

**Comment by pamag** [comment]
## Reviewed
