### ISSUE TITLE
Review  MyProfile Component

### ISSUE THREAD

**Issue by halender** [opencb/jsorolla#394]
## Description

At this moment we have an initial design of the user profile where some info of the user is displayed (including projects and studies that the user has access):

![image](https://user-images.githubusercontent.com/5751201/152026354-436b422e-b964-4501-b441-50cac6ab1bc4.png)

Some users also requested to allow changing their password using the IVA interface, so the user profile is the best place to put the form for changing the password.

Also, this view is in an old component called `iva-profile` that is placed in the `src/sites` folder, not in `src/webcomponents/users`: https://github.com/opencb/jsorolla/blob/cd5573776a19d4340b9919dd2070931a811c2d68/src/sites/iva/iva-profile.js 

## Proposed solution

The proposed solution is to redesign this component using the improved features of `data-form`, adding also support for changing the password of the user in this component. The new component will be called `user-profile` and will be placed in `src/webcomponents/user` folder.

## Technical details

In the OpenCGA REST API we have an endpoint that can be used to change the password of the authenticated user: https://ws.opencb.org/opencga-test/webservices/#!/Users/changePassword

This endpoint requires:
- `user`: user ID.
- `password`: the old password.
- `newPassword`: the new password.

## Tasks

- [x] Create a new `user-profile` component for displaying user info and projects and studies.
- [x] Add new `input-password` element in data-form.
- [x] Allow changing the password in the user profile.
- [x] Remove old `iva-profile` component (moved to obsolete folder).

**Comment by jmjuanes** [comment]
First implementation of the new user profile view:

![image](https://user-images.githubusercontent.com/5751201/152209149-97bbc371-0a5f-4f5c-8ef5-c0d9c57999fb.png)

Added section to change the current password: 

![image](https://user-images.githubusercontent.com/5751201/152209264-023d0ca7-93be-4603-8209-d25bc3939ca3.png)

**Comment by jmjuanes** [comment]
Redesigned profile section:
 
- Added `user-password-change` component to hangle the password change (commit 43a924f).
- Added `user-projects` component for displaying projects that the logged user has access to grouped by owner user (commit dca7e47).
- Added `user-info` component for displaying basic information of the logged user (commit dcf9a8c).

![image](https://user-images.githubusercontent.com/5751201/153409964-034e784f-80bd-4e8f-803a-00269ca3f8e0.png)

![image](https://user-images.githubusercontent.com/5751201/153411938-72f90a2b-6c1c-4f3a-aa48-1921585d18ce.png)

**Comment by jmjuanes** [comment]
Redesigned projects view for adding two groups: **Your projects** and **Shared projects**.

![image](https://user-images.githubusercontent.com/5751201/153474568-b2f514e7-3fb9-492a-a781-b48e551b81e5.png)

**Comment by pamag** [comment]
## Reviewed

IVA commit: 6df12c6cdc47629a3b362fe8150c53debfb501e2
OpenCGA commit: bcbe75e68198a1171ad977e747189ddcdbc74c39

User profile view has been improved and fixed.

Commntes: 
-- projects section: the studies could be on an accordion section (collapsable cards)
-- Pasword resset: It works well 
  - fields can not be emptied 
  
![image](https://user-images.githubusercontent.com/167875/153990270-c9ccc641-e229-42e5-bafc-9af6fe138e47.png)

  -  The two new password fields should de equal.
  
![image](https://user-images.githubusercontent.com/167875/153990415-fb31242e-b63f-4c17-9825-ee1493489de8.png)

  - After the original password and the two new password fields are filled up correctly, still we need to click TWICE in the "change possword"
![change_password](https://user-images.githubusercontent.com/167875/153990903-6a614535-9a0e-4a4c-9671-9f48b3013999.gif)

**Comment by pamag** [comment]
## Reviewed
    OpenCGA commit: bcbe75e68198a1171ad977e747189ddcdbc74c39
    IVA commit: 067443205dc02f14153103605b03174616683ded

FIXED

Note: if a wrong password is introduced in "Current Password" and  the new password is the same that the wrong current password, an error is raised about new and old password should be different instead of raise the error of "wrong current password"
![image](https://user-images.githubusercontent.com/167875/154393047-a2d54194-7521-4a3e-8065-b2dc2b2417d1.png)
