### ISSUE TITLE
Allow providing a server.json file in IVA and REST API apps

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#425]
## Description

To allow embedding IVA and REST API applications into systems like Kubernetes or to replace Swagger in OpenCGA or CellBase webservices, we need to inject some configuration that can not be added to the default `config.js` file. 

## Proposed solution

Allow IVA and REST API applications to check if a file called `server.json` exists in the `/conf` folder, and in that case, overwrite the default configuration with the specified in the file. At this moment, only OpenCGA configuration will be specified in this `server.json` file.

## Technical aspects

At this moment the OpenCGA client initialization is managed in the `connectedCallback` function of both applications: 

https://github.com/opencb/jsorolla/blob/0de5a03a02251ae72ea95ef6e9358a6838a4738f/src/sites/iva/iva-app.js#L303-L332

We will need to wrap the content of this function in the callback of the function that will check if the `server.json` file exists:

```javascript
connectedCallback() {
    super.connectedCallback();

    // Check if server.json file exists
    importJSONFile("./conf/server.json").then(server => {
        // Initialize OpenCGA configuration
        const opencgaHost = server?.host || this.config.opencga.host;
        const opencgaVersion = server?.version || this.config.opencga.version;

        // Initialise clients and create the session
        // ....

    });
}
```

The `importJSONFile` function will return a promise that will resolve with a `server` object containing the content of the `server.json` file if exists, and `null` in case this file does not exist.

## Tasks

- [x] Add `importJSONFile` function to utils.
- [x] Implement in IVA App.
- [x] Implement in REST API App.

**Comment by jmjuanes** [comment]
Example `conf/server.json` file: 

```json
{
    "host": "https://ws.opencb.org/opencga-test",
    "version": "v2",
    "cookie": {
        "prefix": "iva-"
    }
}
```
